export const itemData = {
  pistol: {
    type: "weapon",
    melee: false,
    name: "pistol",
    hudItem: "pistol",
    projectile: "plasma",
    fireMode: "single",
    fireRate: 0.5,
    consumes: 5,
    speedMultiplier: 2,
    lighting: null,
    // origin: "camera",
  },
  rifle: {
    type: "weapon",
    melee: false,
    name: "rifle",
    hudItem: "rifle",
    projectile: "plasma",
    fireMode: "single",
    fireRate: 0.1,
    consumes: 2,
    speedMultiplier: 4,
    lighting: null,
    // origin: "camera",
  },
  shotgun: {
    type: "weapon",
    melee: false,
    name: "shotgun",
    hudItem: "shotgun",
    projectile: "buckshot",
    fireMode: "single",
    fireRate: 1,
    consumes: 2,
    speedMultiplier: 1,
    lighting: { radius: 64, intensity: 2.5, tint: { r: 255, g: 255, b: 255 } },

    // origin: "camera",
  },
};
