export const projectileData = {
  plasma: {
    texture: "Plasma",
    width: 1,
    height: 1,
    scale: 1,
    damage: 10,
    staggerPower: 6,
    knockback: 2,
    speed: 50,
    lifetime: 2,
    collisionRadius: 2,
    collisionHeight: 2,
    collisionOffsetZ: 0,
    lighting: true,
    radius: 1,
    intensity: 1.5,
    tint: { r: 10, g: 100, b: 255 },
    projectileSound: "minigun",
  },

  buckshot: {
    texture: null,
    width: 1,
    height: 1,
    scale: 1,
    damage: 20,
    staggerPower: 20,
    knockback: 20,
    speed: 400,
    lifetime: 0.1,
    collisionRadius: 8,
    collisionHeight: 12,
    collisionOffsetZ: -2,
    lighting: null,
    radius: 1,
    intensity: 1.5,
    tint: { r: 255, g: 100, b: 255 },
    projectileSound: "shotgun",
  },

  enemyBolt: {
    texture: "EnemyBolt",
    width: 1,
    height: 1,
    scale: 8,
    damage: 10,
    staggerPower: 4,
    knockback: 1.5,
    speed: 12,
    lifetime: 4,
    collisionRadius: 8,
    collisionHeight: 8,
    collisionOffsetZ: 0,
    projectileSound: "shotgun",
  },

  rocket: {
    texture: "Rocket",
    width: 1,
    height: 1,
    scale: 12,
    damage: 50,
    staggerPower: 20,
    knockback: 10,
    speed: 8,
    lifetime: 8,
    collisionRadius: 8,
    collisionHeight: 8,
    collisionOffsetZ: 0,
    projectileSound: "shotgun",
  },
};
