export const projectileData = {
  plasma: {
    texture: "Plasma",
    width: 1,
    height: 1,
    scale: 4,
    damage: 10,
    speed: 30,
    lifetime: 2,
    collisionRadius: 2,
    collisionHeight: 8,
    collisionOffsetZ: 0,
    lighting: true,
    radius: 1,
    intensity: 1.5,
    tint: { r: 10, g: 100, b: 255 },
  },

  enemyBolt: {
    texture: "EnemyBolt",
    width: 1,
    height: 1,
    scale: 8,
    damage: 10,
    speed: 12,
    lifetime: 4,
    collisionRadius: 8,
    collisionHeight: 8,
    collisionOffsetZ: 0,
  },

  rocket: {
    texture: "Rocket",
    width: 1,
    height: 1,
    scale: 12,
    damage: 50,
    speed: 8,
    lifetime: 8,
    collisionRadius: 8,
    collisionHeight: 8,
    collisionOffsetZ: 0,
  },
};
