import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// The main game loads scripts as plain ES modules straight in the
// browser -- no bundler, no JSON import assertions (those would also
// break the test suite's plain `node tests/*.test.mjs` runs on this
// Node version). A `export default {...}` sibling module is the one
// format both sides can import with zero special handling, so that's
// what this script produces from each JSON file the editor writes --
// same thing jsonTools/json2js.js did by hand, just pointed at the
// fixed data folders and run as one command instead of one per folder.
//
// It also generates an index.js per registry folder (maps/, entities/)
// that imports every sibling and re-exports a { key: data } registry,
// so sessions.js stops needing a manual entry per file -- adding a map
// or entity dataset is just "drop the JSON here and run this script".
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.resolve(__dirname, "../scripts/data");

// Every JSON file in these folders gets a generated `export default`
// sibling. Only maps/ and entities/ additionally get an index.js
// registry -- templates/ only ever holds the one componentDefaults.json,
// which is imported directly by name, not listed.
const JSON_SOURCE_DIRS = ["maps", "entities", "templates"].map((name) =>
  path.join(dataDir, name),
);

const REGISTRIES = {
  [path.join(dataDir, "maps")]: "maps",
  [path.join(dataDir, "entities")]: "entityDatasets",
};

// Registry keys are exactly the JSON filename (that's what the editor
// names the map/entity set, and what resolveMapData()/resolveEntityData()
// in sessions.js key off), but a filename isn't always a valid JS
// import-binding name -- camelCase it for the identifier only.
function toIdentifier(stem) {
  const camel = stem.replace(/[^a-zA-Z0-9]+(.)?/g, (_, chr) =>
    chr ? chr.toUpperCase() : "",
  );
  return /^[0-9]/.test(camel) ? `_${camel}` : camel || "_";
}

function jsonFilesIn(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((file) => file.toLowerCase().endsWith(".json"))
    .sort();
}

function writeIfChanged(filePath, contents) {
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, "utf8") === contents) {
    return false;
  }
  fs.writeFileSync(filePath, contents);
  return true;
}

let filesWritten = 0;

for (const dir of JSON_SOURCE_DIRS) {
  for (const file of jsonFilesIn(dir)) {
    const jsonPath = path.join(dir, file);
    const jsPath = jsonPath.replace(/\.json$/i, ".js");
    const data = JSON.parse(fs.readFileSync(jsonPath, "utf8"));
    const contents =
      `// AUTO-GENERATED from ${file} by tools/build-data.js -- do not edit by hand.\n` +
      `export default ${JSON.stringify(data, null, 2)};\n`;

    if (writeIfChanged(jsPath, contents)) {
      filesWritten++;
      console.log(`✓ ${path.relative(dataDir, jsonPath)} -> ${path.basename(jsPath)}`);
    }
  }
}

for (const [dir, exportName] of Object.entries(REGISTRIES)) {
  const entries = jsonFilesIn(dir).map((file) => {
    const key = file.replace(/\.json$/i, "");
    return { key, identifier: toIdentifier(key) };
  });

  const imports = entries
    .map((entry) => `import ${entry.identifier} from "./${entry.key}.js";`)
    .join("\n");
  const body = entries
    .map((entry) => `  "${entry.key}": ${entry.identifier},`)
    .join("\n");
  const contents =
    `// AUTO-GENERATED by tools/build-data.js -- do not edit by hand.\n` +
    `${imports}\n\n` +
    `export const ${exportName} = {\n${body}\n};\n`;

  const indexPath = path.join(dir, "index.js");
  if (writeIfChanged(indexPath, contents)) {
    filesWritten++;
    console.log(
      `✓ generated ${path.relative(dataDir, indexPath)} (${entries.length} entr${
        entries.length === 1 ? "y" : "ies"
      })`,
    );
  }
}

console.log(`\n${filesWritten} file(s) written.`);
